"""Kaggle adapter (kernels push).

The job directory is embedded (base64 tar.gz) in a generated script kernel, pushed as a private
kernel with GPU and internet enabled. The script unpacks the job to /kaggle/temp, installs
requirements, runs the entrypoint and copies the declared outputs to /kaggle/working/outputs,
which Kaggle exposes as kernel output.
"""

from __future__ import annotations

import base64
import json
import os
import shutil
import tempfile
from datetime import UTC, timedelta
from pathlib import Path
from typing import Any

from tierhopper import credentials
from tierhopper.adapters.base import (
    AdapterError,
    AttemptPlan,
    AttemptState,
    CreditReading,
    ValidationResult,
)
from tierhopper.models import AttemptStatus, CreditSource, CreditUnit, Provider
from tierhopper.redact import redact

ACCELERATORS = {"T4x2": "NvidiaTeslaT4", "L4": "NvidiaL4X1", "L4x2": "NvidiaL4"}
MAX_EMBED_BYTES = 900 * 1024

_STATUS = {
    "QUEUED": AttemptStatus.QUEUED,
    "NEW_SCRIPT": AttemptStatus.QUEUED,
    "RUNNING": AttemptStatus.RUNNING,
    "COMPLETE": AttemptStatus.SUCCEEDED,
    "ERROR": AttemptStatus.FAILED,
    "CANCEL_REQUESTED": AttemptStatus.CANCELLED,
    "CANCEL_ACKNOWLEDGED": AttemptStatus.CANCELLED,
}

_RUNNER = '''\
# Generated by TierHopper. Do not edit.
import base64, io, json, os, shutil, subprocess, sys, tarfile, time
from pathlib import Path

PACKAGE = "{package}"
COMMAND = {command}
REQUIREMENTS = {requirements}
OUTPUTS = {outputs}
RUNNER_CONFIG = {runner_config}

work = Path("/kaggle/temp/job")
work.mkdir(parents=True, exist_ok=True)
with tarfile.open(fileobj=io.BytesIO(base64.b64decode(PACKAGE)), mode="r:gz") as tar:
    tar.extractall(work, filter="data")
if REQUIREMENTS:
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r", str(work / REQUIREMENTS)], check=True)
started = time.time()
env = {{**os.environ, "TH_RUNNER_CONFIG": RUNNER_CONFIG}}
code = subprocess.run(COMMAND, shell=True, cwd=work, env=env).returncode
out = Path("/kaggle/working/outputs")
out.mkdir(parents=True, exist_ok=True)
for rel in OUTPUTS:
    src = work / rel
    if src.is_dir():
        shutil.copytree(src, out / rel.rstrip("/"), dirs_exist_ok=True)
    elif src.is_file():
        (out / rel).parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, out / rel)
Path("/kaggle/working/tierhopper.json").write_text(json.dumps({{"exit_code": code, "seconds": time.time() - started}}))
sys.exit(code)
'''


def _api():
    """Authenticated KaggleApi using the token from the Keychain (never written to disk by us)."""
    token = credentials.get_secret("kaggle", "api_token")
    if token:
        os.environ["KAGGLE_API_TOKEN"] = token
    from kaggle.api.kaggle_api_extended import KaggleApi

    api = KaggleApi()
    api.authenticate()
    return api


class KaggleAdapter:
    id = "kaggle"

    def validate_credentials(self) -> ValidationResult:
        try:
            q = _api().quota_view()
        except Exception as e:  # noqa: BLE001
            return ValidationResult(False, redact(f"Kaggle auth failed: {e}"))
        if q.gpu_quota is None:
            return ValidationResult(False, "no GPU quota; verify your phone number in Kaggle settings")
        return ValidationResult(True, "Kaggle token is valid and GPU quota is available")

    def credit_remaining(self, provider: Provider, used_usd: float = 0.0) -> CreditReading:
        q = _api().quota_view()
        if q.gpu_quota is None:
            return CreditReading(0.0, CreditUnit.GPU_HOURS, CreditSource.API, total=0.0)
        used = q.gpu_quota.time_used.total_seconds() / 3600
        total = q.gpu_quota.total_time_allowed.total_seconds() / 3600
        resets = q.quota_refresh_time
        if resets is not None and resets.tzinfo is None:
            resets = resets.replace(tzinfo=UTC)
        return CreditReading(max(total - used, 0.0), CreditUnit.GPU_HOURS, CreditSource.API,
                             total=total, resets_at=resets)

    def submit(self, plan: AttemptPlan) -> dict[str, Any]:
        api = _api()
        username = api.config_values.get("username")  # resolved from the token by authenticate()
        if not username:
            raise AdapterError("could not resolve the Kaggle username from the API token")
        spec = plan.spec
        package = plan.package
        if len(package) > MAX_EMBED_BYTES:
            raise AdapterError("job package too large to embed in a Kaggle kernel (limit ~900 KB)")
        accelerator = ACCELERATORS.get(plan.gpu.type)
        if accelerator is None:
            raise AdapterError(f"unsupported Kaggle GPU: {plan.gpu.type}")

        slug = f"th-{plan.attempt_id[:8]}"
        script = _RUNNER.format(
            package=base64.b64encode(package).decode(),
            # repr(): Python literals (json would write `null`/`true`, which are not Python)
            command=repr(plan.command),
            requirements=repr(spec.requirements),
            outputs=repr(list(spec.outputs)),
            runner_config=repr(json.dumps(plan.runner_config)),
        )
        metadata = {
            "id": f"{username}/{slug}",
            "title": slug,
            "code_file": "run.py",
            "language": "python",
            "kernel_type": "script",
            "is_private": True,
            "enable_gpu": True,
            "enable_tpu": False,
            "enable_internet": True,
            "machine_shape": accelerator,
            "dataset_sources": [],
            "competition_sources": [],
            "kernel_sources": [],
            "model_sources": [],
        }
        with tempfile.TemporaryDirectory(prefix="tierhopper-kaggle-") as tmp:
            Path(tmp, "run.py").write_text(script)
            Path(tmp, "kernel-metadata.json").write_text(json.dumps(metadata))
            try:
                resp = api.kernels_push(tmp, timeout=str(spec.timeout_minutes * 60), acc=accelerator)
            except Exception as e:  # noqa: BLE001
                raise AdapterError(redact(f"Kaggle push failed: {e}")) from e
        error = getattr(resp, "error", None)
        if error:
            raise AdapterError(redact(f"Kaggle push rejected: {error}"))
        kernel = getattr(resp, "ref", "") or metadata["id"]
        kernel = kernel.removeprefix("/code/").removeprefix("https://www.kaggle.com/code/").strip("/")
        return {"kernel": kernel, "accelerator": accelerator,
                "url": getattr(resp, "url", None) or f"https://www.kaggle.com/code/{metadata['id']}"}

    def poll(self, ref: dict[str, Any]) -> AttemptState:
        resp = _api().kernels_status(ref["kernel"])
        raw = getattr(resp, "status", None)
        name = getattr(raw, "name", str(raw)).upper()
        status = _STATUS.get(name, AttemptStatus.RUNNING)
        message = getattr(resp, "failure_message", None) or None
        if status == AttemptStatus.FAILED and not message:
            message = self._log_tail(ref["kernel"])
        return AttemptState(status, message=redact(message) if message else None)

    @staticmethod
    def _log_tail(kernel: str) -> str | None:
        """Last lines of the kernel log, so a failure always says why."""
        try:
            with tempfile.TemporaryDirectory(prefix="tierhopper-kaggle-log-") as tmp:
                _api().kernels_output(kernel, tmp, force=True, page_size=200)
                for path in Path(tmp).glob("*.log"):
                    raw = path.read_text(errors="replace")
                    try:
                        text = "".join(str(chunk.get("data", "")) for chunk in json.loads(raw))
                    except (ValueError, AttributeError):
                        text = raw
                    return text.strip()[-2000:] or None
        except Exception:  # noqa: BLE001 - the log is a nicety
            return None
        return None

    def fetch_outputs(self, ref: dict[str, Any], dest: Path, result: dict | None = None) -> list[Path]:
        """Download kernel output; declared outputs land in `dest`, the rest in `dest/_provider`."""
        raw = dest / "_provider"
        raw.mkdir(parents=True, exist_ok=True)
        api = _api()
        token = None
        while True:
            _, token = api.kernels_output(ref["kernel"], str(raw), force=True, page_token=token, page_size=200)
            if not token:
                break
        outputs = raw / "outputs"
        if outputs.is_dir():
            shutil.copytree(outputs, dest, dirs_exist_ok=True)
            shutil.rmtree(outputs)
        return [p for p in dest.rglob("*") if p.is_file()]

    def cancel(self, ref: dict[str, Any]) -> None:
        # The public API has no cancel; the kernel stops at its timeout. Recorded as cancelled locally.
        return None

    def max_session(self, provider: Provider) -> timedelta | None:
        return timedelta(hours=provider.max_session_hours) if provider.max_session_hours else None
