"""State store interface. Implementations: in-memory (tests) and Supabase (production)."""

from __future__ import annotations

from typing import Protocol

from tierhopper.models import Attempt, CreditSnapshot, Event, Job, Project, Provider, Shard


class NotFound(KeyError):
    pass


class Store(Protocol):
    # providers
    def upsert_provider(self, provider: Provider) -> Provider: ...
    def get_provider(self, provider_id: str) -> Provider: ...
    def list_providers(self, status: str | None = None) -> list[Provider]: ...

    # credits
    def add_credit_snapshot(self, snap: CreditSnapshot) -> CreditSnapshot: ...
    def latest_credit(self, provider_id: str) -> CreditSnapshot | None: ...

    # projects / jobs
    def get_or_create_project(self, slug: str) -> Project: ...
    def get_project(self, project_id: str) -> Project: ...
    def create_job(self, job: Job) -> Job: ...
    def update_job(self, job: Job) -> Job: ...
    def get_job(self, job_id: str) -> Job: ...
    def list_jobs(self, status: str | None = None, limit: int = 50) -> list[Job]: ...

    # shards / attempts
    def create_shard(self, shard: Shard) -> Shard: ...
    def update_shard(self, shard: Shard) -> Shard: ...
    def list_shards(self, job_id: str) -> list[Shard]: ...
    def get_shard(self, shard_id: str) -> Shard: ...
    def get_attempt(self, attempt_id: str) -> Attempt: ...
    def create_attempt(self, attempt: Attempt) -> Attempt: ...
    def update_attempt(self, attempt: Attempt) -> Attempt: ...
    def finish_attempt(self, attempt: Attempt) -> bool: ...  # False if another process finished it first
    def list_attempts(self, shard_id: str) -> list[Attempt]: ...
    def list_active_attempts(self) -> list[Attempt]: ...
    def usage_since(self, provider_id: str, since) -> tuple[float, float]: ...
    def list_attempts_since(self, since) -> list[Attempt]: ...

    # events
    def add_event(self, event: Event) -> Event: ...
    def list_events(self, job_id: str, limit: int = 100) -> list[Event]: ...
    def list_events_since(self, type_: str, since) -> list[Event]: ...

    # live telemetry (dashboard)
    def add_metric(self, attempt_id: str, values: dict) -> None: ...
    def add_log_lines(self, attempt_id: str, lines: list[str]) -> None: ...
    def list_log_lines(self, attempt_id: str, limit: int = 200) -> list[str]: ...
    def prune_telemetry(self, before) -> None: ...

    # discovery
    def add_finding(self, finding: dict) -> None: ...
    def list_findings(self, limit: int = 50) -> list[dict]: ...

    # web push (dashboard PWA)
    def list_push_subscriptions(self) -> list[dict]: ...
    def delete_push_subscription(self, endpoint: str) -> None: ...
